ALTER TABLE listings
ADD COLUMN IF NOT EXISTS tour_start_location VARCHAR(255),
ADD COLUMN IF NOT EXISTS tour_end_location VARCHAR(255),
ADD COLUMN IF NOT EXISTS tour_start_date TIMESTAMP,
ADD COLUMN IF NOT EXISTS tour_end_date TIMESTAMP,
ADD COLUMN IF NOT EXISTS tour_capacity INT;
